name: Build, publish and deploy project to UmbHost

on:
  workflow_dispatch:
  push:
    branches: [ master ]
env:
    SolutionName: ${{ secrets.SOLUTION_NAME }}
    BuildPlatform: Any CPU
    BuildConfiguration: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3.0.0
        
        #- name: Setup MSBuild
        #  uses: microsoft/setup-msbuild@v1
          
        #- name: Setup NuGet.exe for use with actions
        #  uses: NuGet/setup-nuget@v1.2.0

        #- name: Create Build Directory
        #  run: mkdir _build

        #- name: Restore Packages
        #  run: nuget restore ${{env.SolutionName}}

        #- name: Replace variables
        #  uses: microsoft/variable-substitution@v1 
        #  with:
        #    files: 'JacksorJacksorUmbraco/appsettings.Production.json'
        #  env:
        #    ConnectionStrings.umbracoDbDSN: ${{ secrets.CONNECTION_STRING }}

        #- name: Build Solution
        #  run: | 
        #    msbuild.exe ${{env.SolutionName}} /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DeleteExistingFiles=True /p:SkipInvalidConfigurations=true /p:IncludeSetAclProviderOnDestination=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:platform="${{env.BuildPlatform}}" /p:configuration="${{env.BuildConfiguration}}" /p:PackageLocation="../_build" /p:EnvironmentName=Production


        # Trying Carl's way
        - name: Set up .NET Core
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 6.0.x

        - name: Build with dotnet
          run: dotnet build --configuration Release

        - name: dotnet publish
          run: dotnet publish -c Release -o JacksorJacksorUmbraco/_build


        - name: Upload artifact for deployemnt
          uses: actions/upload-artifact@v3
          with:
            name: JacksorJacksorUmbraco.zip
            path: "JacksorJacksorUmbraco/_build"
     


  deploy:
    runs-on: windows-latest
    needs: build
    steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          id: download
          with:
            name: JacksorJacksorUmbraco.zip  
            path: "JacksorJacksorUmbraco/_build"

        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1

        - name: Deploy to UmbHost
          uses: UmbHost/umbhost-web-deploy@v1.0.1
          with:
            website-name: ${{ secrets.WEBSITE_NAME }}
            server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
            server-username: ${{ secrets.USERNAME }}
            server-password: ${{ secrets.PASSWORD }}
            source-path: '_build'
            source-fileName: JacksorJacksorUmbraco.zip
