# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
    SolutionName: JacksorJacksorUmbraco
    BuildPlatform: Any CPU
    BuildConfiguration: Release


jobs:
 build:
    runs-on: windows-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: 5.5.0

    - name: Create Build Directory
      run: mkdir _build

    - name: Restore Packages
      run: nuget restore "JacksorJacksorUmbraco"

    - name: Build Solution
      run: | 
        msbuild.exe ${{env.SolutionName}} /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DeleteExistingFiles=True /p:SkipInvalidConfigurations=true /p:IncludeSetAclProviderOnDestination=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:platform="${{env.BuildPlatform}}" /p:configuration="${{env.BuildConfiguration}}" /p:PackageLocation="../_build"
